language: python
services:
  - postgresql
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - DJANGO='django>=1.11,<2.0'
  - DJANGO='django>=2.1,<2.2'
  - DJANGO='django>=2.2,<2.3'
  - DJANGO='django>=3.0,<3.1'
  - DJANGO='--pre django'
matrix:
  allow_failures:
    - env: DJANGO='--pre django'
  exclude:
    - python: "3.5"
      env: DJANGO='django>=3.0,<3.1'
    - python: "3.5"
      env: DJANGO='--pre django'
    - python: "3.8"
      env: DJANGO='django>=1.11,<2.0'
  fast_finish: true
install:
  - psql -c 'CREATE DATABASE "django-cursor-pagination"' -U postgres;
  - pip install $DJANGO
  - pip install psycopg2
  - pip install -e .
script: "./runtests.py"
notifications:
  email: false
